#!/usr/bin/env python

import os
from utils import GhidraExport

def main():
    export = GhidraExport(currentProgram)

    header = (
        "/*\n"
        " Decompilation generated by Ghidra (headless)\n"
        " Program: {}\n"
        "*/\n\n"
    ).format(currentProgram.getName())

    decompiled = "{}{}".format(header, export.get_decompilation())

    out_path = os.path.abspath("./decompiled.c")
    with open(out_path, "w") as f:
        f.write(decompiled)

    print("Wrote decompilation to {}".format(os.path.basename(out_path)))


if __name__ == "__main__":
    main()

